[package]
name = "tasmota-rs"
version = "0.1.1"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "tasmota"

[dependencies]
regex = "1.8"

# used in structs.rs for the regex
lazy_static = "1.4.0"

serde = { version = "1.0.160", features = ["derive"] }
serde_json = "1.0.96"

reqwest = { version = "0.11.16",  features = ["blocking", "json"] }

mac_address = "1.1.4"
ipnet = "2.7.2"

config = { version = "0.13", features = ["json"] }
shellexpand = "3.1"

log = "0.4.17"
pretty_env_logger = "0.4.0"

rayon = "1.7.0"

clap = { version = "4.2.2", features = ["derive"] }
