[package]
name = "tasmota-rs"
version = "0.1.1"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "tasmota"

[dependencies]
regex = "1.10"

# used in structs.rs for the regex
lazy_static = "1.4.0"

serde = { version = "1.0.196", features = ["derive"] }
serde_json = "1.0.114"

reqwest = { version = "0.11.24",  features = ["blocking", "json"] }

mac_address = "1.1.5"
ipnet = "2.9.0"

config = { version = "0.14", features = ["json"] }
shellexpand = "3.1"

log = "0.4.20"
pretty_env_logger = "0.5.0"

rayon = "1.8.1"

clap = { version = "4.5.1", features = ["derive"] }
