[package]
name = "tasmota-rs"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "tasmota"

[dependencies]
regex = "1.6"

# used in structs.rs for the regex
lazy_static = "1.4.0"

serde = { version = "1.0.142", features = ["derive"] }
serde_json = "1.0.83"

reqwest = { version = "0.11.11",  features = ["blocking", "json"] }

mac_address = "1.1.2"
ipnet = "2.3.1"

config = { version = "0.13", features = ["json"] }
shellexpand = "2.1"

log = "0.4.17"
pretty_env_logger = "0.4.0"

rayon = "1.5.3"

clap = { version = "3.2.17", features = ["derive"] }
