[package]
name = "tasmota-rs"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "0.2"

# used in structs.rs for the regex
lazy_static = "1.4.0"

serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.67"

reqwest = { version = "0.11.4",  features = ["blocking", "json"] }

mac_address = "1.1.3"
ipnet = "2.3.1"

config = { version = "0.11", features = ["json"] }
shellexpand = "2.0"

log = "0.4.14"
pretty_env_logger = "0.4.0"

rayon = "1.5.1"

clap = { version = "3.0.14", features = ["derive"] }
