[package]
name = "tasmota-rs"
version = "0.1.1"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "tasmota"

[dependencies]
regex = "1.7"

# used in structs.rs for the regex
lazy_static = "1.4.0"

serde = { version = "1.0.147", features = ["derive"] }
serde_json = "1.0.88"

reqwest = { version = "0.11.12",  features = ["blocking", "json"] }

mac_address = "1.1.4"
ipnet = "2.5.1"

config = { version = "0.13", features = ["json"] }
shellexpand = "2.1"

log = "0.4.17"
pretty_env_logger = "0.4.0"

rayon = "1.5.3"

clap = { version = "4.0.22", features = ["derive"] }
