[package]
name = "tasmota-rs"
version = "0.1.1"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "tasmota"

[dependencies]
regex = "1.9"

# used in structs.rs for the regex
lazy_static = "1.4.0"

serde = { version = "1.0.183", features = ["derive"] }
serde_json = "1.0.105"

reqwest = { version = "0.11.18",  features = ["blocking", "json"] }

mac_address = "1.1.5"
ipnet = "2.8.0"

config = { version = "0.13", features = ["json"] }
shellexpand = "3.1"

log = "0.4.19"
pretty_env_logger = "0.5.0"

rayon = "1.7.0"

clap = { version = "4.3.22", features = ["derive"] }
