---
name: Rust Testing
on:
  push:
  pull_request:

jobs:
  cargo_test:
    name: "Rust Build and Test"
    env:
      SCCACHE_GHA_ENABLED: true
      RUSTC_WRAPPER: sccache
      CARGO_INCREMENTAL: 0
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Setup sccache
        uses: mozilla-actions/sccache-action@v0.0.8
      - name: Build
        run: |
          cargo build
          cargo build --release
      - name: Test
        run: |
          cargo test
          cargo test --release
